# Generated by Django 5.2.14 on 2026-06-02 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_barteritem_status_barteritem_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barteritem',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('like_new', 'Like New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('not_applicable', 'Not Applicable (Service)')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='barteritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('item_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_as_item_1', to='api.barteritem')),
                ('item_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_as_item_2', to='api.barteritem')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api.barteroffer')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
