# Generated by Django 6.0.5 on 2026-06-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_barteritem_condition_barteritem_image_and_more'),
        ('api', '0004_otpverification'),
    ]

    operations = [
    ]
