# Generated by Django 6.0.5 on 2026-06-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chatmessage_options_chatmessage_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterinterest',
            name='offered_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_offers', to='api.barteritem'),
        ),
    ]
