# Generated by Django 6.0.5 on 2026-06-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_barterinterest_offered_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='barteritem',
            name='age_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barteritem',
            name='item_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='barteritem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='BarterItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.barteritem')),
            ],
        ),
    ]
