# Generated by Django 5.2.15 on 2026-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_coin_balance_cointransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coin_balance',
            field=models.IntegerField(default=10),
        ),
    ]
