# Generated by Django 5.2.15 on 2026-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_coin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('purchased', 'Purchased')], max_length=10),
        ),
    ]
