# Generated by Django 6.0.7 on 2026-07-19 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_chatroom_barter_interest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barterinterest',
            name='coins_offered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barterinterest',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='barterinterest',
            name='proposal_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='barterinterest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('contract_pending', 'Contract Pending'), ('contract_signed', 'Contract Signed'), ('ready_for_shipping', 'Ready for Shipping'), ('pickup_ready', 'Pickup Ready'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='contract_pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('offered_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_offered', to='api.barteritem')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='api.barterinterest')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_receiver', to=settings.AUTH_USER_MODEL)),
                ('requested_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_requested', to='api.barteritem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(blank=True, default='')),
                ('coin_difference', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('requester_signed', models.BooleanField(default=False)),
                ('requester_signed_at', models.DateTimeField(blank=True, null=True)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('receiver_signed', models.BooleanField(default=False)),
                ('receiver_signed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='api.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.trade')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('shipping', 'Courier Delivery'), ('meetup', 'Meet In Person')], default='shipping', max_length=20)),
                ('carrier', models.CharField(blank=True, default='', max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('shipping_notes', models.TextField(blank=True, default='')),
                ('tracking_status', models.CharField(blank=True, default='Pending Shipment', max_length=100)),
                ('meetup_location', models.CharField(blank=True, default='', max_length=255)),
                ('meetup_date', models.DateField(blank=True, null=True)),
                ('meetup_time', models.TimeField(blank=True, null=True)),
                ('meetup_notes', models.TextField(blank=True, default='')),
                ('meetup_confirmed_requester', models.BooleanField(default=False)),
                ('meetup_confirmed_receiver', models.BooleanField(default=False)),
                ('qr_verification_code', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='api.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('communication', models.IntegerField(default=5)),
                ('item_accuracy', models.IntegerField(default=5)),
                ('experience', models.CharField(blank=True, default='', max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('would_trade_again', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_trade_reviews', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.trade')),
            ],
            options={
                'unique_together': {('trade', 'reviewer')},
            },
        ),
    ]
