# Generated by Django 6.0.7 on 2026-07-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_barterinterest_coins_offered_barterinterest_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeevent',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradelogistics',
            name='trade',
        ),
        migrations.AlterUniqueTogether(
            name='tradereview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tradereview',
            name='reviewee',
        ),
        migrations.RemoveField(
            model_name='tradereview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='tradereview',
            name='trade',
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='TradeAgreement',
        ),
        migrations.DeleteModel(
            name='TradeEvent',
        ),
        migrations.DeleteModel(
            name='TradeLogistics',
        ),
        migrations.DeleteModel(
            name='TradeReview',
        ),
    ]
