# Generated by Django 5.2.15 on 2026-07-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_tradeevent_trade_remove_tradelogistics_trade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('terms', models.JSONField(default=list)),
                ('signed_a', models.BooleanField(default=False)),
                ('signed_b', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barter_interest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='api.barterinterest')),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_party_a', to=settings.AUTH_USER_MODEL)),
                ('party_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_party_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
