# Generated by Django 5.2.15 on 2026-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='logistics_status',
            field=models.CharField(default='preparing', max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='shipping_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
