# Generated by Django 6.0.7 on 2026-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_a_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_a_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_b_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_b_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
