# Generated by Django 6.0.7 on 2026-07-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_contract_signed_a_ip_contract_signed_a_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='evidence_image',
            field=models.FileField(blank=True, null=True, upload_to='dispute_evidence/'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
