# Generated by Django 6.0.7 on 2026-07-31 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_dispute_evidence_image_dispute_is_escalated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='evidence_image',
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='api.dispute')),
            ],
        ),
    ]
