# Generated by Django 5.2.15 on 2026-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coin_balance',
            field=models.IntegerField(default=100),
        ),
    ]
