# Generated by Django 6.0.7 on 2026-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userprofile_coin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='handshake_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='meetup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='meetup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
