# Generated by Django 6.0.7 on 2026-08-14 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_trade_handshake_pin_trade_meetup_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.trade'),
        ),
    ]
