# Generated by Django 5.2.15 on 2026-08-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userprofile_is_premium'),
        ('api', '0028_userreview_trade'),
    ]

    operations = [
    ]
