# Generated by Django 6.0.7 on 2026-08-23 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_otpverification_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='barteritem',
            name='is_boosted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='barteritem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived'), ('traded', 'Traded'), ('reserved', 'Reserved')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='barteritem',
            index=models.Index(fields=['latitude', 'longitude'], name='api_barteri_latitud_964bef_idx'),
        ),
        migrations.AddIndex(
            model_name='tradecoinreservation',
            index=models.Index(fields=['proposal', 'status'], name='api_tradeco_proposa_ca9761_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', 'status'], name='api_wallett_user_id_f65e19_idx'),
        ),
    ]
