# Generated by Django 6.0.7 on 2026-08-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_barteritem_is_boosted_alter_barteritem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='price_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in INR', max_digits=10),
        ),
    ]
