# Generated by Django 6.0.7 on 2026-08-23 05:36

from django.db import migrations

def migrate_legacy_trade_data(apps, schema_editor):
    BarterOffer = apps.get_model('api', 'BarterOffer')
    TradeTransaction = apps.get_model('api', 'TradeTransaction')
    BarterInterest = apps.get_model('api', 'BarterInterest')
    Trade = apps.get_model('api', 'Trade')
    UserReview = apps.get_model('api', 'UserReview')
    
    offer_to_interest_map = {}
    
    # 1. Migrate BarterOffers -> BarterInterests
    for offer in BarterOffer.objects.all():
        interest = BarterInterest.objects.filter(
            requester=offer.sender,
            receiver=offer.receiver,
            requested_item=offer.requested_item,
            offered_item=offer.offered_item
        ).first()
        
        if not interest:
            status_map = {
                'pending': 'pending',
                'accepted': 'accepted',
                'rejected': 'declined',
                'countered': 'countered',
                'cancelled': 'cancelled'
            }
            new_status = status_map.get(offer.status, 'pending')
            
            interest = BarterInterest.objects.create(
                requester=offer.sender,
                receiver=offer.receiver,
                requested_item=offer.requested_item,
                offered_item=offer.offered_item,
                status=new_status,
                proposal_message=offer.message or '',
                created_at=offer.created_at,
                updated_at=offer.updated_at
            )
            
        offer_to_interest_map[offer.id] = interest
    
    # 2. Migrate TradeTransactions -> Trades
    for transaction in TradeTransaction.objects.all():
        offer = transaction.offer
        interest = offer_to_interest_map.get(offer.id)
        
        if not interest:
            continue
            
        trade = Trade.objects.filter(proposal=interest).first()
        
        if not trade:
            trade = Trade.objects.create(
                proposal=interest,
                requested_listing=interest.requested_item,
                offered_listing=interest.offered_item,
                requester=interest.requester,
                receiver=interest.receiver,
                status='completed',
                created_at=transaction.completed_at,
                completed_at=transaction.completed_at
            )
        
        # 3. Update UserReviews pointing to the offer
        UserReview.objects.filter(offer=offer).update(trade=trade)

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_wallettransaction_price_inr'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_trade_data, reverse_migration),
    ]
