# Generated by Django 6.0.7 on 2026-08-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_consolidate_trade_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradetransaction',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='tradetransaction',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='tradetransaction',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='tradetransaction',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='tradetransaction',
            name='user_2',
        ),
        migrations.DeleteModel(
            name='BarterOffer',
        ),
        migrations.DeleteModel(
            name='TradeTransaction',
        ),
    ]
