# Generated by Django 6.0.7 on 2026-08-23 05:54

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    for category in Category.objects.all():
        if not category.slug:
            category.slug = slugify(category.name)
            category.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_category_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
