# Generated by Django 6.0.7 on 2026-08-23 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_populate_category_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('COIN_PURCHASE', 'Coin Purchase'), ('COIN_REDEMPTION', 'Coin Redemption'), ('TRADE_TRANSFER', 'Trade Transfer'), ('TRADE_ESCROW', 'Trade Escrow'), ('LISTING_BOOST', 'Listing Boost'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('SYSTEM_BONUS', 'System Bonus')], max_length=50)),
                ('previous_balance', models.IntegerField()),
                ('amount_changed', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User, Admin, or System who initiated the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audits_actor', to=settings.AUTH_USER_MODEL)),
                ('reference_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.wallettransaction')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_audits_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_user', '-timestamp'], name='api_financi_target__e6b778_idx'), models.Index(fields=['action_type'], name='api_financi_action__4284f1_idx')],
            },
        ),
    ]
