"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

Environment variables:
  SECRET_KEY          (REQUIRED in prod) Django secret key
  DEBUG               (default: True locally, set to False in prod)
  ALLOWED_HOSTS       (REQUIRED in prod) comma-separated hostnames
  ENVIRONMENT         set to "production" to enable prod-safe defaults
  CORS_ALLOWED_ORIGINS (REQUIRED in prod) comma-separated origins
  DATABASE_URL        (optional) PostgreSQL connection string; falls back to SQLite
  REDIS_URL           (optional) Redis URL; falls back to InMemoryChannelLayer
  CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET
  EMAIL_HOST_USER / EMAIL_HOST_PASSWORD / EMAIL_HOST / EMAIL_PORT / EMAIL_USE_TLS
  RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET
"""

import os
import logging
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

# ─── helpers ──────────────────────────────────────────────────────────────────

def _env_bool(key, default=False):
    val = os.environ.get(key, "").strip().lower()
    if not val:
        return default
    return val in ("1", "true", "yes", "on")

def _env_list(key, default=""):
    raw = os.environ.get(key, default).strip()
    return [x.strip() for x in raw.split(",") if x.strip()]

IS_PRODUCTION = os.environ.get("ENVIRONMENT", "").strip().lower() == "production"

# ─── Core security settings ───────────────────────────────────────────────────

# REQUIRED in production. Locally falls back to the insecure dev key.
_dev_secret = "django-insecure-e-$hl5ue6$h$f=c33*1!(c=h8__ee4%#k(%imhp4za6gs6l!t_"
SECRET_KEY = os.environ.get("SECRET_KEY", _dev_secret)

if IS_PRODUCTION and SECRET_KEY == _dev_secret:
    raise RuntimeError(
        "SECRET_KEY must be set to a strong random value in production. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# DEBUG defaults to True for local dev; must be False in production.
DEBUG = _env_bool("DEBUG", default=not IS_PRODUCTION)

if IS_PRODUCTION and DEBUG:
    raise RuntimeError("DEBUG must be False in production. Set DEBUG=False in your environment.")

# ALLOWED_HOSTS: locally accepts all, prod requires explicit list.
if IS_PRODUCTION:
    ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS")
    if not ALLOWED_HOSTS:
        raise RuntimeError("ALLOWED_HOSTS must be set in production (comma-separated list of hostnames).")
else:
    ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", default="*")

# ─── CORS ────────────────────────────────────────────────────────────────────

if IS_PRODUCTION:
    # REQUIRED in production: explicitly list allowed origins.
    # e.g.  CORS_ALLOWED_ORIGINS=https://myapp.com,https://www.myapp.com
    _prod_origins = _env_list("CORS_ALLOWED_ORIGINS")
    if not _prod_origins:
        raise RuntimeError(
            "CORS_ALLOWED_ORIGINS must be set in production (comma-separated list of origins)."
        )
    CORS_ALLOWED_ORIGINS = _prod_origins
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # Dev: allow all origins for convenience.
    CORS_ALLOW_ALL_ORIGINS = True

# ─── Application definition ───────────────────────────────────────────────────

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'django_celery_beat',

    # Local apps
    'api',
    'chat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# ─── Database ─────────────────────────────────────────────────────────────────

_db_url = os.environ.get("DATABASE_URL", "")
if _db_url:
    # Simple PostgreSQL URL parsing: postgres://user:pass@host:port/dbname
    import urllib.parse as _up
    _u = _up.urlparse(_db_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _u.path.lstrip('/'),
            'USER': _u.username or '',
            'PASSWORD': _u.password or '',
            'HOST': _u.hostname or 'localhost',
            'PORT': str(_u.port or 5432),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ─── Auth & JWT ───────────────────────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        # Custom scopes for auth endpoints
        'login': '10/minute',
        'register': '5/minute',
        'otp': '5/minute',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ─── i18n ─────────────────────────────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ─── Static & media ───────────────────────────────────────────────────────────

STATIC_URL = 'static/'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET')

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ─── Email ────────────────────────────────────────────────────────────────────

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ─── Third-party keys ─────────────────────────────────────────────────────────

RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')

BOOST_COST = 100
BOOST_DURATION_DAYS = 7

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Channel Layers (Redis → InMemory fallback) ───────────────────────────────

logger = logging.getLogger(__name__)

_redis_url = os.environ.get("REDIS_URL", "")
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        },
    }
else:
    # Try a local Redis on 6379 (dev convenience)
    try:
        import socket as _socket
        _s = _socket.socket(_socket.AF_INET, _socket.SOCK_STREAM)
        _s.settimeout(0.5)
        _s.connect(("127.0.0.1", 6379))
        _s.close()
        CHANNEL_LAYERS = {
            'default': {
                'BACKEND': 'channels_redis.core.RedisChannelLayer',
                'CONFIG': {'hosts': [("127.0.0.1", 6379)]},
            },
        }
    except Exception:
        if not DEBUG:
            from django.core.exceptions import ImproperlyConfigured
            raise ImproperlyConfigured("REDIS_URL must be set outside of DEBUG/local environments.")
        
        logger.warning("Redis unavailable — falling back to InMemoryChannelLayer.")
        CHANNEL_LAYERS = {
            'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
        }

# ─── File upload limits ───────────────────────────────────────────────────────

DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400   # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400   # 25 MB

# ─── Celery Settings ─────────────────────────────────────────────────────────

# In production, ensure REDIS_URL is used for Celery as well
CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'deactivate-expired-boosts': {
        'task': 'api.tasks.deactivate_expired_boosts',
        'schedule': crontab(minute='*/5'),
    },
}
