services:
  - type: web
    name: barter-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
